In [1]:
from scipy.io import loadmat
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt  #importing libraray
import math
import scipy.optimize as opt

In [2]:


def sigmoid(x):
    return 1 / (1 + np.exp(-x))  #sigmoid fn
def sigmoidgrad(z): #it compute derivate of sigmoid of the fn
    return sigmoid(z)*(1-sigmoid(z))

print(sigmoidgrad(0))


0.25


In [3]:
data = loadmat('C:\\Users\\PRASHANT\\Desktop\\coding dec19\\file_neural\\ex3data1.mat')

* data is present inside a matlab file
* data['X'] is 5000 X 400 size matrix 
* 400 column is for 20 X 20 pixel image
* each pixel contain value denoting intensity from 0 to 255
* output data['y'] is 5000 X 1 matrix , which actually represnt that no 
* we take out data['X'] as X and add a column of ones hence X becomes 5000 X 401 matrix
* we take out data['y'] in Y
* we replace all element in Y whose value is 10 by 0
* we comput y1 matrix which is 5000 X 10 matrix which contain 1 at poition which is value of Y in that row
* we compute A2 matrix which result of forward propagation and it 5000 X 10 matrix
* from A2 we compute ouput matrix which contain digit from 1 to 9 in 5000 X 1 matrix
* we compare output with Y matrix to find accuracy

In [4]:
data #data is present in matlab file


{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 '__globals__': [],
 'X': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'y': array([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [5]:
print(np.max(data['X']))
print(np.min(data['X']))

1.127688299158888
-0.13196323019852488


In [6]:
type(data)

dict

In [7]:

theta1=np.random.uniform(-0.12,0.12,(25,401))
theta2=np.random.uniform(-0.12,0.12,(10,26))
print(theta1.shape)
print(theta2.shape)

(25, 401)
(10, 26)


In [8]:
print(theta1)

[[ 0.02121746 -0.04191756 -0.00162958 ...  0.02838664 -0.01442904
  -0.04294873]
 [ 0.10835141  0.10358258  0.02757069 ...  0.07669612  0.06125085
   0.0587826 ]
 [ 0.03479958  0.10306612  0.03748438 ...  0.07220853  0.10319697
   0.09113343]
 ...
 [-0.02126523 -0.09880793 -0.08041321 ...  0.08138417  0.01291037
  -0.00080085]
 [-0.06933516  0.00795416  0.03793541 ... -0.03618126 -0.07964092
  -0.03984486]
 [-0.08912568  0.03800917 -0.03705041 ...  0.11019239  0.04858443
   0.07421192]]


In [9]:
XX=data['X']
print(XX.shape,type(XX))
#=annots['y']
Y = data['y']
print(Y)
print(Y.shape,type(Y))
np.place(Y, Y == 10, 0)
print(Y[4000:5000,:])

(5000, 400) <class 'numpy.ndarray'>
[[10]
 [10]
 [10]
 ...
 [ 9]
 [ 9]
 [ 9]]
(5000, 1) <class 'numpy.ndarray'>
[[8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8

In [10]:
m,n=XX.shape
x0=np.ones([m,1])

print(x0.shape)

(5000, 1)


In [11]:
X=np.hstack([x0,XX])
print(X.shape)

(5000, 401)


In [12]:


print(Y.shape,type(Y))
print(X.shape,type(X))
print(Y)

(5000, 1) <class 'numpy.ndarray'>
(5000, 401) <class 'numpy.ndarray'>
[[0]
 [0]
 [0]
 ...
 [9]
 [9]
 [9]]


In [13]:
n_label=10


print(theta1.shape)
print(theta2.shape)

print(X.shape)

print(type(X))

(25, 401)
(10, 26)
(5000, 401)
<class 'numpy.ndarray'>


In [14]:
A1=sigmoid(X.dot(theta1.T))
print(A1.shape)
a1=np.ones([A1.shape[0],1])
A1=np.hstack([a1,A1])

(5000, 25)


In [15]:


#print("A1 is ",A1)
print(A1.shape)
A2=sigmoid(A1.dot(theta2.T))
print(A2.shape)
output=np.argmax(A2, axis=1)
print(Y)
output=output.reshape((Y.shape))
print(output)




(5000, 26)
(5000, 10)
[[0]
 [0]
 [0]
 ...
 [9]
 [9]
 [9]]
[[3]
 [3]
 [3]
 ...
 [3]
 [3]
 [3]]


In [16]:
print("Training accuracy:", str(100 * np.mean(output == Y)) + "%")

Training accuracy: 10.0%


In [17]:
print(Y.shape)
print(output.shape)


(5000, 1)
(5000, 1)


In [18]:
y1=np.zeros([m,10])
for u in range(0,5000):
    y1[u,Y[u]]=1
print(y1)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [19]:
print(output.shape)
print(y1.shape)
print(A2.shape)

(5000, 1)
(5000, 10)
(5000, 10)


In [20]:
J_cost1=(y1*np.log(A2))+((1-y1)*np.log(1-A2)) 
#J_cost2=sum(np.square(thete1))+sum(np.square(theta2))
J_final=np.sum(J_cost1)/(-m)
print("unregularised cost is ",J_final)

unregularised cost is  7.00921031136778


In [21]:
X.shape

(5000, 401)

In [22]:
def cost_reg(theta1,theta2,X,y1):
    
    
    
    lambda1=1
    A11=sigmoid(X.dot(theta1.T))
    
    a1=np.ones([A11.shape[0],1])
    A1=np.hstack([a1,A11])
    A2=sigmoid(A1.dot(theta2.T))
   
    J_cost1=np.sum((y1*np.log(A2))+((1-y1)*np.log(1-A2)) )
    J_cost2=np.sum(np.square(theta1[:,1:401]))+np.sum(np.square(theta2[:,1:25]))
    J_final=(J_cost1)/(-m)+(lambda1/(2*m))*J_cost2
    print("regularised cost is ",J_final)
    return J_final

print(cost_reg(theta1,theta2,X,y1))

regularised cost is  7.014078390881729
7.014078390881729


In [23]:
def compute_grad(theta1,theta2,X,y1,alpha):
    m=5000
    
    #forward propagation
    A11=sigmoid(X.dot(theta1.T))
   
    a1=np.ones([A11.shape[0],1])
    A1=np.hstack([a1,A11])
    A2=sigmoid(A1.dot(theta2.T))
   
      
     #backward propagation   
    delta3=A2-y1                                           #dz2
    delta2=((delta3)@(theta2[:,1:26]))*(sigmoidgrad(A11))  #dz1
                                        
   
    Delta1=((delta2.T)@X)/m #a1=x    #dw1 
    Delta2=((delta3.T)@A1)/m #a2=A1  #dw2 
    ttheta1=np.hstack([np.zeros([theta1.shape[0],1]),theta1[:,1:]]) #db1
    ttheta2=np.hstack([np.zeros([theta2.shape[0],1]),theta2[:,1:]]) #db2
                                        
    Theta1_grad = Delta1 +  ttheta1/m  # 1 is for lambda  in numerator ie lambda1=1
    Theta2_grad = Delta2 +  ttheta2/m
    
    theta2=theta2-(alpha)*Theta2_grad
    theta1=theta1-(alpha)*Theta1_grad
   
                                       
    #grad = np.concatenate([Theta1_grad.ravel(), Theta2_grad.ravel()])

    return [theta2,theta1]
    
    
    
    
    

In [24]:
y1=np.zeros([m,10])
for u in range(0,5000):
        y1[u,Y[u]]=1



In [25]:
alpha=0.03 #initially i take large value of alpha ie lerning rate
for i1 in range(0,4000):
    [theta2,theta1]=compute_grad(theta1,theta2,X,y1,alpha)
    if i1%100==0:
        #print(theta2)
        cost_reg(theta1,theta2,X,y1)

regularised cost is  6.644365070511889
regularised cost is  3.2473209182871012
regularised cost is  3.224754954372173
regularised cost is  3.1963374851336908
regularised cost is  3.1572748855750232
regularised cost is  3.102962839658982
regularised cost is  3.0297611301422243
regularised cost is  2.9366432492729295
regularised cost is  2.8258163868568067
regularised cost is  2.7021788719252777
regularised cost is  2.5725357344332975
regularised cost is  2.4442690210368228
regularised cost is  2.3234035501916055
regularised cost is  2.213361333637348
regularised cost is  2.115091881014269
regularised cost is  2.027959252820613
regularised cost is  1.9506127813278769
regularised cost is  1.881548771677525
regularised cost is  1.8193904158131495
regularised cost is  1.7629906055260098
regularised cost is  1.711442114680886
regularised cost is  1.664046309521059
regularised cost is  1.620268123007355
regularised cost is  1.579691620582054
regularised cost is  1.5419829923437567
regularised

In [26]:
alpha=0.001
for i1 in range(0,5000):
    [theta2,theta1]=compute_grad(theta1,theta2,X,y1,alpha)
    if i1%500==0:
        #print(theta2)
        cost_reg(theta1,theta2,X,y1)

regularised cost is  1.1707498789417012
regularised cost is  1.1682395684225806
regularised cost is  1.165746328224307
regularised cost is  1.1632699775481605
regularised cost is  1.1608103404486112
regularised cost is  1.158367245468334
regularised cost is  1.1559405253813109
regularised cost is  1.1535300170015252
regularised cost is  1.1511355610316887
regularised cost is  1.1487570019366016


In [27]:
alpha=0.0003
for i1 in range(0,5000):
    [theta2,theta1]=compute_grad(theta1,theta2,X,y1,alpha)
    if i1%500==0:
        #print(theta2)
        cost_reg(theta1,theta2,X,y1)

regularised cost is  1.1463974848362277
regularised cost is  1.1456916826776262
regularised cost is  1.1449872802732926
regularised cost is  1.1442842737054368
regularised cost is  1.1435826590840201
regularised cost is  1.1428824325465023
regularised cost is  1.142183590257601
regularised cost is  1.1414861284090534
regularised cost is  1.1407900432193854
regularised cost is  1.1400953309336819


In [28]:
alpha=0.0001  #what we are doing is decreasing alpha to avoid overshotting
for i1 in range(0,5000):
    [theta2,theta1]=compute_grad(theta1,theta2,X,y1,alpha)
    if i1%500==0:
        #print(theta2)
        cost_reg(theta1,theta2,X,y1)

regularised cost is  1.1394029113710369
regularised cost is  1.1391721000709718
regularised cost is  1.1389414403541398
regularised cost is  1.1387109320843531
regularised cost is  1.1384805751257439
regularised cost is  1.13825036934276
regularised cost is  1.1380203146001688
regularised cost is  1.1377904107630517
regularised cost is  1.137560657696807
regularised cost is  1.1373310552671467


In [29]:
    A11=sigmoid(X.dot(theta1.T))
   
    a1=np.ones([A11.shape[0],1])
    A1=np.hstack([a1,A11])
    A2=sigmoid(A1.dot(theta2.T))
   
    output=np.argmax(A2, axis=1)
    
    output=output.reshape((Y.shape))
    cost_reg(theta1,theta2,X,y1)

regularised cost is  1.1371020620938372


1.1371020620938372

In [30]:
print("Training accuracy:", str(100 * np.mean(output == Y)) + "%") #str is used to convert float to string to concat % with it

Training accuracy: 86.56%
