In [1]:
from scipy.io import loadmat
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt  #importing libraray
import math
import scipy.optimize as opt

In [2]:


def sigmoid(x):
    return 1 / (1 + np.exp(-x))  #sigmoid fn
def sigmoidgrad(z): #it compute derivate of sigmoid of the fn
    return sigmoid(z)*(1-sigmoid(z))

print(sigmoidgrad(0))


0.25


In [3]:
data = loadmat('C:\\Users\\PRASHANT\\Desktop\\coding dec19\\file_neural\\ex3data1.mat')

* data is present inside a matlab file
* data['X'] is 5000 X 400 size matrix 
* 400 column is for 20 X 20 pixel image
* each pixel contain value denoting intensity from 0 to 255
* output data['y'] is 5000 X 1 matrix , which actually represnt that no 
* we take out data['X'] as X and add a column of ones hence X becomes 5000 X 401 matrix
* we take out data['y'] in Y
* we replace all element in Y whose value is 10 by 0
* we comput y1 matrix which is 5000 X 10 matrix which contain 1 at poition which is value of Y in that row
* we compute A2 matrix which result of forward propagation and it 5000 X 10 matrix
* from A2 we compute ouput matrix which contain digit from 1 to 9 in 5000 X 1 matrix
* we compare output with Y matrix to find accuracy

In [4]:
data #data is present in matlab file


{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 '__globals__': [],
 'X': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'y': array([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [5]:
print(np.max(data['X']))
print(np.min(data['X']))

1.127688299158888
-0.13196323019852488


In [6]:
type(data)

dict

In [7]:
X=data['X']
X=X.T # X is 400 X 5000
Y=data['y']

In [8]:
m=5000
theta1=np.random.uniform(-0.12,0.12,(25,400))
b1=np.zeros([25,1])
#z1= theta1 @X +b1
#A1= sigmoid(z1)
theta2=np.random.uniform(-0.12,0.12,(25,25))
b2=np.zeros([25,1])
#z2= theta2 @ A1 +b2
# A2= sigmoid(z2) 
theta3=np.random.uniform(-0.12,0.12,(10,25))
b3=np.zeros([10,1])
#z3= theta3 @ A2 +b3
# A3= sigmoid(z3) 
print(X.shape)
print(theta1.shape,b1.shape,theta2.shape,b2.shape,theta3.shape,b3.shape)


(400, 5000)
(25, 400) (25, 1) (25, 25) (25, 1) (10, 25) (10, 1)


In [9]:
print(X.shape,Y.shape)

(400, 5000) (5000, 1)


In [10]:

print(Y.shape,type(Y))
np.place(Y, Y == 10, 0)
print(Y[0:5000,:])

(5000, 1) <class 'numpy.ndarray'>
[[0]
 [0]
 [0]
 ...
 [9]
 [9]
 [9]]


In [11]:


print(Y.shape,type(Y))
print(X.shape,type(X))
print(Y)

(5000, 1) <class 'numpy.ndarray'>
(400, 5000) <class 'numpy.ndarray'>
[[0]
 [0]
 [0]
 ...
 [9]
 [9]
 [9]]


In [12]:
n_label=10


print(theta1.shape)
print(theta2.shape)
print(theta3.shape)

print(X.shape)

print(type(X))

(25, 400)
(25, 25)
(10, 25)
(400, 5000)
<class 'numpy.ndarray'>


In [13]:
A0=X
print("A0 shape ",A0.shape)
Z1=theta1@A0+b1
A1=sigmoid(Z1)
print("A1 shape ",A1.shape)


A0 shape  (400, 5000)
A1 shape  (25, 5000)


In [14]:


#print("A1 is ",A1)
print(A1.shape)
Z2=theta2@A1+b2
A2=sigmoid(Z2)
print("A2 shape ",A2.shape)
Z3=theta3@A2+b3
A3=sigmoid(Z3)
print("A3 shape ",A3.shape)
output=np.argmax(A3, axis=0)
print("output shape ",output.shape)
print(Y)
output=output.reshape((Y.shape))
print("output shape",output.shape)
print(output)




(25, 5000)
A2 shape  (25, 5000)
A3 shape  (10, 5000)
output shape  (5000,)
[[0]
 [0]
 [0]
 ...
 [9]
 [9]
 [9]]
output shape (5000, 1)
[[3]
 [3]
 [3]
 ...
 [3]
 [3]
 [3]]


In [15]:
print("Training accuracy:", str(100 * np.mean(output == Y)) + "%")

Training accuracy: 10.0%


In [16]:
print(Y.shape)
print(output.shape)


(5000, 1)
(5000, 1)


In [17]:
m=5000
y1=np.zeros([10,m])
for u in range(0,5000):
    y1[Y[u],u]=1
print(y1)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]]


In [18]:
print(output.shape)
print(y1.shape)
print(A3.shape)

(5000, 1)
(10, 5000)
(10, 5000)


In [19]:
J_cost1=(y1*np.log(A3))+((1-y1)*np.log(1-A3)) 
#J_cost2=sum(np.square(thete1))+sum(np.square(theta2))
J_final=np.sum(J_cost1)/(-m)
print("unregularised cost is ",J_final)

unregularised cost is  7.324443116988227


In [20]:
X.shape

(400, 5000)

In [21]:
def cost_reg(theta1,b1,theta2,b2,theta3,b3,X,y1):
    
    
    
    lambda1=1
    A0=X
    
    Z1=theta1@A0+b1
    A1=sigmoid(Z1)
    Z2=theta2@A1+b2
    A2=sigmoid(Z2)
    
    Z3=theta3@A2+b3
    A3=sigmoid(Z3)
    
    
    
    
    
    
    """"
    
    A11=sigmoid(X.dot(theta1.T))
    
    a1=np.ones([A11.shape[0],1])
    A1=np.hstack([a1,A11])
    A2=sigmoid(A1.dot(theta2.T))
   """
    J_cost1=np.sum((y1*np.log(A3))+((1-y1)*np.log(1-A3)) )
    J_cost2=np.sum(np.square(theta1))+np.sum(np.square(theta2))+np.sum(np.square(theta3))
    J_final=(J_cost1)/(-m)+(lambda1/(2*m))*J_cost2
    print("regularised cost is ",J_final)
    return J_final

print(cost_reg(theta1,b1,theta2,b2,theta3,b3,X,y1))

regularised cost is  7.329572425777809
7.329572425777809


In [22]:
def compute_grad(theta1,b1,theta2,b2,theta3,b3,X,y1,alpha):
    m=5000
    
    #forward propagation
    A0=X #400 X 5000
    
    Z1=theta1@A0+b1 #25 X 5000
    A1=sigmoid(Z1) #25 X 50000
    Z2=theta2@A1+b2 # 25 X 5000
    A2=sigmoid(Z2)# 25 X 5000
   
    Z3=theta3@A2+b3     #10 X 5000
    A3=sigmoid(Z3)      #10 X 5000
    
    
    
    '''
    A11=sigmoid(X.dot(theta1.T))
   
    a1=np.ones([A11.shape[0],1])
    A1=np.hstack([a1,A11])
    A2=sigmoid(A1.dot(theta2.T))
   '''
      
     #backward propagation  
    
    delta3=A3-y1 #10 X 5000
    Delta3=(delta3@(A2.T))/m #a3=A1  #dw3      10 X 25
    db3=np.sum(delta3,axis=1)/m  # 10 X 1
    db3=db3.reshape((10,1))
    
    #delta2=((delta3)@(theta3))*(sigmoidgrad(A2)) # 10 X5000
    delta2=((theta3.T)@(delta3))*(sigmoidgrad(A2)) # 25 X5000
    Delta2=(delta2@(A1.T))/m #a1=A1  #dw2        25 X 25
    db2=np.sum(delta2,axis=1) /m        # 25 X 1
    db2=db2.reshape((25,1))
    
    delta1=((theta2.T)@(delta2))*(sigmoidgrad(A1)) # 25 X5000
    Delta1=(delta1@(A0.T))/m #a1=A1  #dw2        25 X 400
    db1=np.sum(delta1,axis=1) /m        # 25 X 1
    db1=db1.reshape((25,1))
    
    theta3=theta3-(alpha)*Delta3
    theta2=theta2-(alpha)*Delta2
    theta1=theta1-(alpha)*Delta1
    b1=b1-(alpha)*db1
    b2=b2-(alpha)*db2
    b3=b3-(alpha)*db3
    return [theta1 ,theta2 ,theta3, b1, b2, b3]
    
    """"
    delta1=((delta2)@(theta2))*(sigmoidgrad(A1))   # 10 X 
    Delta1=((delta2.T)@X)/m #a0=x    #dw1 
    db1=np.sum(delta1,axis=0,keepdim=True)
    
    """
    
    
    
    
    
    '''
    delta3=A2-y1                                           #dz2
    delta2=((delta3)@(theta2[:,1:26]))*(sigmoidgrad(A11))  #dz1
                                        
   
    Delta1=((delta2.T)@X)/m #a1=x    #dw1 
    Delta2=((delta3.T)@A1)/m #a2=A1  #dw2 
    ttheta1=np.hstack([np.zeros([theta1.shape[0],1]),theta1[:,1:]]) #db1
    ttheta2=np.hstack([np.zeros([theta2.shape[0],1]),theta2[:,1:]]) #db2
                                        
    Theta1_grad = Delta1 +  ttheta1/m  # 1 is for lambda  in numerator ie lambda1=1
    Theta2_grad = Delta2 +  ttheta2/m
    
    theta2=theta2-(alpha)*Theta2_grad
    theta1=theta1-(alpha)*Theta1_grad
   
                                       
    #grad = np.concatenate([Theta1_grad.ravel(), Theta2_grad.ravel()])

    return [theta2,theta1]
    
  '''  
    
    
    

In [23]:
y1=np.zeros([10,m])
for u in range(0,5000):
        y1[Y[u],u]=1



In [24]:
alpha=0.1 #initially i take large value of alpha ie lerning rate
for i1 in range(0,3000):
    [theta1 ,theta2 ,theta3, b1, b2, b3]=compute_grad(theta1,b1,theta2,b2,theta3,b3,X,y1,alpha)
    if i1%500==0:
        #print(theta2)
        cost_reg(theta1,b1,theta2,b2,theta3,b3,X,y1)

regularised cost is  6.158676790765292
regularised cost is  3.2523283754526355
regularised cost is  3.233916650948533
regularised cost is  2.925384975926681
regularised cost is  2.3556350310111545
regularised cost is  2.1713501513324074


In [25]:
alpha=0.03 #initially i take large value of alpha ie lerning rate
for i1 in range(0,3000):
    [theta1 ,theta2 ,theta3, b1, b2, b3]=compute_grad(theta1,b1,theta2,b2,theta3,b3,X,y1,alpha)
    if i1%500==0:
        #print(theta2)
        cost_reg(theta1,b1,theta2,b2,theta3,b3,X,y1)

regularised cost is  1.8896915256585474
regularised cost is  1.7813733684795834
regularised cost is  1.6794535506851969
regularised cost is  1.5925272378625344
regularised cost is  1.5256831216656632
regularised cost is  1.4776586476864393


In [26]:
alpha=0.001
for i1 in range(0,5000):
    [theta1 ,theta2 ,theta3, b1, b2, b3]=compute_grad(theta1,b1,theta2,b2,theta3,b3,X,y1,alpha)
    if i1%1000==0:
        #print(theta2)
        cost_reg(theta1,b1,theta2,b2,theta3,b3,X,y1)

regularised cost is  1.4441634272439239
regularised cost is  1.4423298709737613
regularised cost is  1.4405405039010482
regularised cost is  1.438794335104414
regularised cost is  1.437090402047085


In [27]:
alpha=0.0003
for i1 in range(0,12000):
    [theta1 ,theta2 ,theta3, b1, b2, b3]=compute_grad(theta1,b1,theta2,b2,theta3,b3,X,y1,alpha)
    if i1%1000==0:
        #print(theta2)
        cost_reg(theta1,b1,theta2,b2,theta3,b3,X,y1)

regularised cost is  1.4354289181891902
regularised cost is  1.4349380368026807
regularised cost is  1.4344507660754235
regularised cost is  1.4339670820074997
regularised cost is  1.433486960786251
regularised cost is  1.4330103787843265
regularised cost is  1.4325373125577856
regularised cost is  1.4320677388442997
regularised cost is  1.4316016345614653
regularised cost is  1.4311389768052278
regularised cost is  1.430679742848423
regularised cost is  1.4302239101394272


In [28]:
alpha=0.0001  #what we are doing is decreasing alpha to avoid overshotting
for i1 in range(0,16000):
    [theta1 ,theta2 ,theta3, b1, b2, b3]=compute_grad(theta1,b1,theta2,b2,theta3,b3,X,y1,alpha)
    if i1%2000==0:
        #print(theta2)
        cost_reg(theta1,b1,theta2,b2,theta3,b3,X,y1)

regularised cost is  1.4297717568162533
regularised cost is  1.4294719857064675
regularised cost is  1.42917369991586
regularised cost is  1.4288768929414521
regularised cost is  1.4285815583140333
regularised cost is  1.428287689598054
regularised cost is  1.4279952803915195
regularised cost is  1.4277043243258876


In [29]:
    A0=X #400 X 5000
    print("A0 shape ",A0.shape)
    Z1=theta1@A0+b1 #25 X 5000
    A1=sigmoid(Z1) #25 X 50000
    Z2=theta2@A1+b2 # 25 X 5000
    A2=sigmoid(Z2)# 25 X 5000
    print("A2 shape ",A2.shape)
    Z3=theta3@A2+b3     #10 X 5000
    A3=sigmoid(Z3)
   
    output=np.argmax(A3, axis=0)
    
    output=output.reshape((Y.shape))
    cost_reg(theta1,b1,theta2,b2,theta3,b3,X,y1)

A0 shape  (400, 5000)
A2 shape  (25, 5000)
regularised cost is  1.427414959460134


1.427414959460134

In [30]:
print("Training accuracy:", str(100 * np.mean(output == Y)) + "%") #str is used to convert float to string to concat % with it

Training accuracy: 78.32000000000001%
